# Generated by Django 6.0 on 2026-01-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta (ya no viene de QuickBooks)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='qb_item_id',
            field=models.CharField(blank=True, help_text='ID del Item en QuickBooks (opcional)', max_length=50, null=True, unique=True),
        ),
    ]
